# Generated by Django 2.2.5 on 2020-01-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam ab neque culpa amet dignissimos aliquid assumenda officiis? Hic, architecto cupiditate quasi voluptate quaerat asperiores adipisci expedita quidem doloribus ex vel.'),
            preserve_default=False,
        ),
    ]
